variables:
  IMAGE_NAME: alparslanu6347/python-app-gitlab  
  IMAGE_TAG: python-demo-v$CI_PIPELINE_IID  # CI_PIPELINE_IID : predefined variable

stages:
  - test
  - build
  - deploy

run_test:
  stage: test
  image: python:3.8-alpine 
  script:
    - python --version
    - pip3 --version
    - pwd
    - whoami

build_image:
  stage: build
  image: docker:24.0.5 
  services:
    - docker:24.0.5-dind
  variables:
    DOCKER_TLS_CERTDIR: "/certs"
  before_script:
    - docker login -u $DOCKER_HUB_USER -p $DOCKER_HUB_PWD  
  script:  
    - docker build -t $IMAGE_NAME:$IMAGE_TAG .
    - docker push $IMAGE_NAME:$IMAGE_TAG

deploy:
  stage: deploy
  before_script:
    - chmod 400 $SSH_KEY
  script:
    - ssh -o StrictHostKeyChecking=no -i $SSH_KEY ubuntu@54.89.207.38 "
      docker login -u $DOCKER_HUB_USER -p $DOCKER_HUB_PWD &&
      docker rm -f $(docker ps -aq) || docker image prune -af &&
      docker run -d -p 8080:8080 $IMAGE_NAME:$IMAGE_TAG"
